//! Test vectors for rescue over BLS12-381 scalar field.
//! The parameters and test vectors for these parameters are generated by the
//! the `rescue_bls.sage`
//! from [this repo](https://github.com/alexandroszacharakis8/Marvellous)
//! commit todo: push the script for bls
//!
//! The test vectors correspond to
//! - the permutation of [0,0,0,0]
//! - four random inputs sampled to be used with the fixed key variant
//! - four random key-input pairs
//! The random seed used is 0.

use midnight_curves::bls12_381::{Fq as Scalar};
use ff::Field;
use crate::rescue::primitive::RescueState;

type InputOutputPair<F> = (RescueState<F>, RescueState<F>);
type KeyedInputOutputPair<F> = (RescueState<F>, RescueState<F>, RescueState<F>);

// BLS TEST VECTORS

// 1. input = [0, 0, 0, 0]
//    output = [
//                 20414261918868254201092725419878310501749198711524286293792872443468262687492,
//                 23357377611741139872346647741946814883249326613459731625640812933564805770328,
//                 11219501918282617308418049294362287084798317583992094406147091534559291474781,
//                 6246109855103774742817388721826577301738431548687699159864715465901992321423,
//             ]
//
// 2. input =  [
//                 10503412003881821869136456373522787233679370364645479538240052532105577893546,
//                 8757260086840876529736133106643790240807422174769617215153045897800511486174,
//                 12611587488970178020234800979835231446181428428390492190317266241455236381927,
//                 2726134449038804621085856805106069212936857402995849498810918644948057672840,
//             ]
//    outut =  [
//                 27432244639932421511850297279031727626054531386182637415268197140399128006751,
//                 20177231650329177011921672612952329020776390071365767996569498008973079360464,
//                 24869376210116516331014720913215106874251498798755446339213159851624547212606,
//                  2936704480442293820539510337720171577401864923205166888084338890286577460644,
//             ]
//
// 3. input =  [
//                 22093610244669648513559347206865582926378887565514373648608310448177968783509,
//                 10112616694260675116360998006629449094860077106159662085987322930049251613850,
//                 13308557346712452248984606949470970039680682303088581303976062622507988636378,
//                 11133988682274425766829344931307896214908557213042084888408990231188559153311,
//             ]
//    outut =  [
//                 23390381605193145609802788656392492327667109188241063045302706205496288693945,
//                 20476040847052847136497144025069135336630548059691252899327920177759605160012,
//                 12867738395497314876959805300477882847137996984116723268842902393022147839657,
//                 28361702286975059676649769328903435857595149747785170482767871097851145185662,
//             ]
//
// 4. input =  [
//                 28452351074088404870595113088265946180812344089079838371557378198296097729744,
//                  7736550645179879490301510434595978746218704273345567808193336746199816709599,
//                 26268803994255445256927800235153092296491857030533210878261482329451392271434,
//                 10371842046307891656872259413343384216503090847933120557222269312228987914117,
//             ]
//    outut =  [
//                 14570839471522255322809050853799477790955774297942857121340669374829636594284,
//                 12692737137343769731065605435402142521465459962559598444566105402217756469820,
//                  3308568110353383806516337624053179274542555903739314156200131031429235495753,
//                 26557340456617147969095395564947470833196734760928300982277136375833811869548,
//             ]
//
// 5. input =  [
//                 25465926896625650486266638278568966960765656669528575454671989732972779415079,
//                 15141795091485059050172110218271856953723167353885766634713783166036404160286,
//                 15652134582247166179660237247645554155115583953143450303782581401101606646948,
//                 27937567782359138067205323556510402976385854662549744359929872146968231869239,
//             ]
//    outut =  [
//                 15865977017803218518926854847629135492666528214288059012991730934109472674601,
//                 27160878257783862614568338233010961117648394219135380059356777030082518514543,
//                 20277769155718299929899669374483449334660941359573961204056541343969497625186,
//                 15389831853393818192027743958259589864161298558336674115539261306710557732681,
//             ]

pub(super) const BLS_TEST_VECTORS: [InputOutputPair<Scalar>; 5] = [
    // [0, 0, 0, 0]
    (
        [
            Scalar::ZERO,
            Scalar::ZERO,
            Scalar::ZERO,
            Scalar::ZERO,
        ],
        [
            Scalar::from_raw([
                0x09d9c9c46ce84304,
                0x91f022121094b24d,
                0xbf3fa67979d79a23,
                0x2d221012b64c4547,
            ]),
            Scalar::from_raw([
                0x2fdd227215dd6c58,
                0x9d4a421cae079863,
                0xaa5487e0d5b9fa47,
                0x33a3cea70394ca00,
            ]),
            Scalar::from_raw([
                0xde847c286969835d,
                0x7b1d9a3653e77caf,
                0x3730525b6cad23bb,
                0x18ce03573abc0f6a,
            ]),
            Scalar::from_raw([
                0x708c08dce308218f,
                0x097e1fabba18c3cb,
                0x1f79bbac06d010ee,
                0xdcf2c42ec98873c,
            ]),
        ],
    ),
    // random pair 1,
    (
        [
            Scalar::from_raw([
                0xe26f4d7a85460eaa,
                0x86744ac52ec64fe4,
                0x9d75f642b36c144e,
                0x1738b874147c8cb1,
            ]),
            Scalar::from_raw([
                0x7277152ce39978de,
                0x147c14a994f6f089,
                0x45570348e1e2ce95,
                0x135c6efdc5d5fc52,
            ]),
            Scalar::from_raw([
                0x8a1e09a8c16cfce7,
                0x531672187c6c29bc,
                0x69b4715c67d3b522,
                0x1be1e7d2d717d114,
            ]),
            Scalar::from_raw([
                0xa61421b06a574c88,
                0x9e7bd97ae5e21c18,
                0x38eb03eca2b19d6d,
                0x606effaa8e5c4b8,
            ]),
        ],
        [
            Scalar::from_raw([
                0xfa51efe633f7505f,
                0xa21bcbc56c16c644,
                0x5fd50f1da2d118d2,
                0x3ca619a974bc0354,
            ]),
            Scalar::from_raw([
                0xdd76e22ada1e33d0,
                0xa5cebcd0f0ef0fb7,
                0x1ed82d48cc6ca6d1,
                0x2c9be88d6996e8a2,
            ]),
            Scalar::from_raw([
                0xa55109aaebfbdd3e,
                0xc8620e0acb6dc261,
                0x2cf90ac750ee224f,
                0x36fb917005f2ce04,
            ]),
            Scalar::from_raw([
                0xca85befba317a5a4,
                0xd0b14fa422bd8238,
                0x51775e1bccd79568,
                0x67e1da73750ee16,
            ]),
        ],
    ),
    // random pair 2
    (
        [
            Scalar::from_raw([
                0x568f054cd07f2095,
                0x8a88ecdfcde4c94f,
                0xe2ceb1efd5c4d06c,
                0x30d88a4e1aac61f9,
            ]),
            Scalar::from_raw([
                0xa61cfa97709d1c9a,
                0xea29189b334a8f10,
                0x1d68adf37c685111,
                0x165b89c86b40f58c,
            ]),
            Scalar::from_raw([
                0xf6705a1b693b52da,
                0x37cb0e9412e7ea85,
                0x898a18ee768437f2,
                0x1d6c6063ac0990fc,
            ]),
            Scalar::from_raw([
                0x85f6a31425f4c89f,
                0xe5b3f10126c71783,
                0x77fba097a63e5ffc,
                0x189d9d41050f4744,
            ]),
        ],
        [
            Scalar::from_raw([
                0x5027c529e1cf4eb9,
                0xe9378c52aa3a15ff,
                0xc7c9f830d703984d,
                0x33b67ca12b490c14,
            ]),
            Scalar::from_raw([
                0xebb1a8391c16f84c,
                0xb67fb84d3a512734,
                0xbd7b4e721e4f43e3,
                0x2d45074684229a17,
            ]),
            Scalar::from_raw([
                0xa66d4eca9e51c6a9,
                0x486cf0546cc89873,
                0x570b88a0531329c3,
                0x1c72e1c00528c478,
            ]),
            Scalar::from_raw([
                0x064eee4c1df9697e,
                0xe9f8745daf0b692f,
                0xcb36f6f24f6b555e,
                0x3eb42795ab0ad3eb,
            ]),
        ],
    ),
    // random pair 3
    (
        [
            Scalar::from_raw([
                0x1ed8ed466a042cd0,
                0x2e07bd59ead588d0,
                0x7b8cf636067c2ce8,
                0x3ee775c40e25e4da,
            ]),
            Scalar::from_raw([
                0x5a4bc62ccdeda5df,
                0x514cdb9a1329807c,
                0x8697579ee6afa910,
                0x111abb8461cea64a,
            ]),
            Scalar::from_raw([
                0x58db3d3a6aa6044a,
                0xba434fbea5c261d1,
                0x09b6f175e833d05a,
                0x3a139dbd7789c5e1,
            ]),
            Scalar::from_raw([
                0x89fcceb6e9564785,
                0x3bcbcd0c167c0fc5,
                0x01268ff693e46938,
                0x16ee412b1f0959b3,
            ]),
        ],
        [
            Scalar::from_raw([
                0x29dc924ae183aa6c,
                0x05efa44d0e96753e,
                0xbf362c6d1eeb3fee,
                0x2036cd89e26e33e3,
            ]),
            Scalar::from_raw([
                0x9f5276fb9681aa3c,
                0xa6fb7c98424569f1,
                0x09a9d4e9a82fd5e5,
                0x1c0fd5aa96c4e128,
            ]),
            Scalar::from_raw([
                0x72622971639e5349,
                0x2a4c1b09eaffe58f,
                0x5b297338ce87fddc,
                0x750954bd9522f87,
            ]),
            Scalar::from_raw([
                0x1307d69cef41df6c,
                0xd4865f355c6ffe05,
                0xe06983a039d6b14d,
                0x3ab6ec09ad03fe1a,
            ]),
        ],
    ),
    // random pair 4
    (
        [
            Scalar::from_raw([
                0x514123a606de2627,
                0x541a7a88b74b2d8b,
                0xe3ad96e8265f67f6,
                0x384d342ec779b772,
            ]),
            Scalar::from_raw([
                0x9c3b8590ebc9471e,
                0x0fa85c4d17c2571e,
                0xd5f9f41fe577940a,
                0x2179f3cadb9c0ca2,
            ]),
            Scalar::from_raw([
                0x72678b6d6220f4a4,
                0x99e6f0c4dcf5db17,
                0xed53eb388d4fd5af,
                0x229acb52a37a4b66,
            ]),
            Scalar::from_raw([
                0x5b4a7ae08da8fb37,
                0x407a54bc33b7dc30,
                0xec0280574d11176b,
                0x3dc41a5e8925c535,
            ]),
        ],
        [
            Scalar::from_raw([
                0xf937c2c933f1d329,
                0xb21ee733d72622e0,
                0x8e6e3a4c5a7f36c9,
                0x2313d3236937ee6f,
            ]),
            Scalar::from_raw([
                0xf7ca71cf6a3efb6f,
                0x3b6fb603171846b4,
                0xe52a99ee038620df,
                0x3c0c8326eb1efca0,
            ]),
            Scalar::from_raw([
                0x84bcfa514994b262,
                0x6317bab6d7333f5a,
                0x12d6e770906fcec5,
                0x2cd4cf84bf006883,
            ]),
            Scalar::from_raw([
                0x50aeea13efa42f49,
                0x16ece8aa663f243e,
                0x1ea8ea5a165e23c5,
                0x2206560dafc0ca19,
            ]),
        ],
    ),
];

// BLS KEYED TEST VECTORS

// 1. key =    [
//                 9735478625688776342504896978379841742965837616380352057079874461875789097195,
//                 17087431511896246789736190796874464064651731370772551315276497213671482793943,
//                 26376073975946691223326437799468266967048011870951893215096247908492841902209,
//                 387706885957693912692721132937120610856967845773737144113025850924713946821,
//             ]
//    input =  [
//                  13800110934263900829736547636480558823416593346067925954706625603035004175201,
//                  17266707156787988303430542879805062962682145221062582776637558985248988097643,
//                  25274641600872663135067681934115536110351522308426344030634297743559499723935,
//                  27928826283442343904809527188082157607383923746068747148873571860757008328691,
//             ]
//    outut =  [
//                  9946089548756104628909582665043284368674005738492652949198176289453455378710,
//                  14867866984468843369081099697781232554617827526811986933468224674662815657700,
//                  17387561424171701203214213468459699744584943132347826204292251692466948647227,
//                  21625427450553410918545042645107272723745880880353382876158896203739384362831,
//             ]
//
// 2. key =    [
//                  25739840654216625744346619974063418060677013759774566696181651954697296526852,
//                  4291382637378481380777284116901922671423106832662186265201778173719788710510,
//                  22947984490713745848909804463206456937800890538031121766097442250418970200369,
//                  17803406184090168953188033265372518218789110015185155327845426680543139560307,
//             ]
//    input =  [
//                  15535532729336990180007932137889150830230689525567685181242310027815384572257,
//                  11079317424316823249480597466897758874241162340924731331598896028636215747548,
//                  14673455925603428716221610257943921400506348833890594775170360498951806725310,
//                  21888121508472356028581016934006435148009959965053223632068404671283863565502,

//             ]
//    outut =  [
//                  4477745708769415391102435300684614413610162401047503027945321951145159419194,
//                  20507832953188396709324987368679215909744976183595562153590365020505802521285,
//                  11148620848985622549532435286512614163470513945684859043253021142774726717160,
//                  3392497833157687866261672223559154379838783922450067803279145991894834682249,
//             ]
//
// 3. key =    [
//                  18494987523639838336846482969527229581369431150125709653190308894195416952566,
//                  16968313411071307992842139532445540884596211442782987568738182059819377763052,
//                  19783180118221045508580338402017871892105969485346941791126032281345771287624,
//                  22049972730747207916841389876043468867411006200281936547940924965259791532646,
//             ]
//    input =  [
//                  753603390665604828640897329815500328493651890780248694491867880679308023151,
//                  16967482062189308116075447064503125131062868986617977590594574701884463834000,
//                  20584251648916684216613762859076453606081767314047097960492634864163444974187,
//                  6679968807624469997992790804513668104698637896294545510437431042325217201451,
//             ]
//    outut =  [
//                  27821583795910711979542913535303889060011823596510730625719795942603384588752,
//                  2406887837695785153747437661842415200655789156924827167682566308660864907903,
//                  5923943203701022522319973254318510775609105335775302936516366014756716166973,
//                  12802086115268704145231443271120181148540932656949222787233177239199574017141,
//             ]
//
// 4. key =    [
//                  5958248350689383180364554007710156328272042298682540590332939563065255997838,
//                  6098500189784380128583943790444670211659416948580542105639529878564056262168,
//                  8420431053795640010153426033398514251414205220028882621889359637665360535602,
//                  18117445988124932704535398845261801473825970717003845084230958290645301324452,
//             ]
//    input =  [
//                  16499300248516203563964514151397727235110590059957171679470220263256327969953,
//                  7642500501568358536888265380038915718902650424925213105080534770178779636732,
//                  8010316018403783583303055331612197557140010304839553552304636691052287401490,
//                  4921586151021337356014854053613497308281468660558864978732657662967854608359,
//             ]
//    outut =  [
//                  5819578910527978655578116546512515524642289636256446791616233791233746911534,
//                  7102365201130967306715835266882412710548785587793597763872407273176357295547,
//                  23344204237294494158214599470155372674477464845643931071956917095214152224407,
//                  22035843361038170511321637922855609556127976875752592928124069246289692498210,
//             ]
pub(super) const BLS_TEST_VECTORS_KEYED: [KeyedInputOutputPair<Scalar>; 4] = [
    // random tuple 1,
    (
        [
            Scalar::from_raw([
                0x18f03fc25d83e8eb,
                0xa36ae18f35d7e41e,
                0xaac8505911e193d9,
                0x158615ebfb9fd0a6,
            ]),
            Scalar::from_raw([
                0x80637c4c37e31fd7,
                0x9b0277be15a01514,
                0x6e712f630821451b,
                0x25c724bca23dd918,
            ]),
            Scalar::from_raw([
                0xfbc4db32a784e081,
                0x9cca73ce81b289ed,
                0x3aaf51ac58e8a4f5,
                0x3a50542e39c618bd,
            ]),
            Scalar::from_raw([
                0x6c601761d6d4aec5,
                0xd4d595dc28dcc52d,
                0x09f932fe33e49c00,
                0xdb6f2fa91bdda8,
            ]),
        ],
        [
            Scalar::from_raw([
                0x9d6c044c86dc8361,
                0x908d52706c235d57,
                0xc3f081d4185ae16f,
                0x1e829603934dacde,
            ]),
            Scalar::from_raw([
                0x242453711f726c6b,
                0xd7ccd8cf05cc6cec,
                0xc959acd5ca0aa19f,
                0x262c9c23e179d4b6,
            ]),
            Scalar::from_raw([
                0xab1ec920a68c349f,
                0x23141bb30611715b,
                0x434b49ea644dd727,
                0x37e0f0b0d2e2a0b9,
            ]),
            Scalar::from_raw([
                0xf340e30d95fba7f3,
                0x71c4ab82c1fe7893,
                0x8fd3641e22604dcd,
                0x3dbf27ce51fbcf8a,
            ]),
        ],
        [
            Scalar::from_raw([
                0xd8fdc2ab15530916,
                0x3dbb0e8d9bf56dc7,
                0x71f4c02d85564008,
                0x15fd49854b9b6acc,
            ]),
            Scalar::from_raw([
                0x8475525b4d186ee4,
                0xd748903c4c13016f,
                0xf24a8ae1af5ba125,
                0x20deea1ca9f8276f,
            ]),
            Scalar::from_raw([
                0x2c55cbf65cada93b,
                0x53b3df76a9210115,
                0x74c050ca8b44d78d,
                0x267102d1ccc838cc,
            ]),
            Scalar::from_raw([
                0xd1460fc2bd99b74f,
                0xe7daa3f2c2e32389,
                0x88c04c7a9da49721,
                0x2fcf8ee51bbe5793,
            ]),
        ],
    ),
    // random tuple 2
    (
        [
            Scalar::from_raw([
                0x3d27362f90b5be04,
                0x447c6ac43182f69c,
                0x01239694590c8859,
                0x38e83bc8b92d1aae,
            ]),
            Scalar::from_raw([
                0xf2c4384cd8b0ea6e,
                0x2c61797f8b9d100f,
                0x82a589f322e32543,
                0x97cd624bc3468f1,
            ]),
            Scalar::from_raw([
                0xd353cfcbf5208931,
                0xbb4ef0c30a7e7c81,
                0xbe1e58cf79b2121d,
                0x32bc19543037b128,
            ]),
            Scalar::from_raw([
                0xdcd772aa44db7b73,
                0x7d033af696a7f2cb,
                0x30a3c129cb34ab86,
                0x275c5eed364ea122,
            ]),
        ],
        [
            Scalar::from_raw([
                0x973be4cf5724e161,
                0x88a1ed205768b244,
                0x5f170862795209e1,
                0x2258ccc789e3551d,
            ]),
            Scalar::from_raw([
                0xbed730ad11afa3dc,
                0x57bc0dccc7f197d0,
                0x12f6d47f24e589f7,
                0x187eabe35b609a78,
            ]),
            Scalar::from_raw([
                0xf95f92c57d1f2cbe,
                0x30ffcece173962dd,
                0x17372824d02102ae,
                0x2070e1b9b5fce7b9,
            ]),
            Scalar::from_raw([
                0x0ccdea3e160d34be,
                0x419247538ba716b7,
                0xfe1e2c0b303e5e6e,
                0x30643cdd431f1514,
            ]),
        ],
        [
            Scalar::from_raw([
                0x200df0dfec45e53a,
                0x7b039b56f2ffdf8a,
                0xe27bafbf1869d865,
                0x9e650733de7bbd7,
            ]),
            Scalar::from_raw([
                0x842f1c53902fbac5,
                0x733c7bfc13d8c9ea,
                0xd384408bf44329b5,
                0x2d5705a945b9c4e2,
            ]),
            Scalar::from_raw([
                0x7064c0be06daeee8,
                0x8f71db724d33b4f8,
                0x9d294dbccfaaefb2,
                0x18a5e5523f554625,
            ]),
            Scalar::from_raw([
                0xa5d080b108911989,
                0xe4da95a7749f334b,
                0x008d8c0ec5a8a653,
                0x78015f24a179703,
            ]),
        ],
    ),
    // random tuple 3
    (
        [
            Scalar::from_raw([
                0x11a008351e59eef6,
                0x3f309ccd04008824,
                0x4a5bf3bdf09ad90f,
                0x28e3cabecbb44fc6,
            ]),
            Scalar::from_raw([
                0xcd9dc4885a2a22ec,
                0x5e1c7f553f49a66a,
                0x9f4c0cc188b8c4e4,
                0x2583b99cb61cb54b,
            ]),
            Scalar::from_raw([
                0xf5b477856429b448,
                0x39ce4c90a234d79a,
                0x52412e95c6e871ac,
                0x2bbce215bf22e360,
            ]),
            Scalar::from_raw([
                0x27b557936e838266,
                0x17db7b0a1baca30a,
                0x7a0b69b16827078d,
                0x30bfd7a0c0f75f5d,
            ]),
        ],
        [
            Scalar::from_raw([
                0x204f8e441820556f,
                0x0b1c3296c5881aca,
                0x599e2e360fd1d61d,
                0x1aa863f517fe1bc,
            ]),
            Scalar::from_raw([
                0x9e96d8643efee390,
                0x2bc4f3bc3dedc38d,
                0x7fbf2008733484a9,
                0x25834128447b957e,
            ]),
            Scalar::from_raw([
                0x22ec157173f3626b,
                0x3c11f55cf422c14e,
                0x06bd49fa2e8c6daa,
                0x2d8246083c0e6466,
            ]),
            Scalar::from_raw([
                0x63d19ccc772ecd2b,
                0x18a43b2e47e6764b,
                0xda04250ced3aeaee,
                0xec4ba75e05c470f,
            ]),
        ],
        [
            Scalar::from_raw([
                0xe1dacd6298d289d0,
                0x46762d7423396448,
                0xb7c6e89302286fd0,
                0x3d827559606739b1,
            ]),
            Scalar::from_raw([
                0xa23fdf67a9dc7a7f,
                0xf270a278f3a0dd9c,
                0x30409d3677b2142d,
                0x552400fb7491fe6,
            ]),
            Scalar::from_raw([
                0xdaaed5f8c92e3f3d,
                0x998eae42bce5348a,
                0xe7da2b41092f0b35,
                0xd18d541acc6c210,
            ]),
            Scalar::from_raw([
                0xa3391b3150c64475,
                0x0b41dd2556bb3b54,
                0x30d538f458b1dfce,
                0x1c4db9559a95b9ea,
            ]),
        ],
    ),
    // random tuple 4
    (
        [
            Scalar::from_raw([
                0x839ebd799319318e,
                0x7a0a1dae9c79d6f6,
                0xefe33249b856eaf9,
                0xd2c3fc24c085a1d,
            ]),
            Scalar::from_raw([
                0x56d72cd3c0e6e618,
                0xc265044c284edb5f,
                0x5c03166f198a0c65,
                0xd7ba0f823a066f9,
            ]),
            Scalar::from_raw([
                0x68d9b079820e6032,
                0x231d8c83c55c7b0d,
                0x6369a633dbfbed5a,
                0x129dcb8a8fd0ea19,
            ]),
            Scalar::from_raw([
                0xca87ddb5961beaa4,
                0x5f24caf341df414e,
                0x68b19754eee9d26b,
                0x280e1c6cf0626684,
            ]),
        ],
        [
            Scalar::from_raw([
                0x96d326bd1d77dca1,
                0xd985f46bc3f8a634,
                0xbf7f6e699fefbf22,
                0x247a45e3a36ac6b1,
            ]),
            Scalar::from_raw([
                0x96a50b78ca81e3fc,
                0x81e14d6fddba6acd,
                0x3aaa19c521a50612,
                0x10e58082aba5455b,
            ]),
            Scalar::from_raw([
                0xd6f0d1df74029e12,
                0x22fa44067f8f0dde,
                0x78a859c17cce6321,
                0x11b5ad9e71b2b18f,
            ]),
            Scalar::from_raw([
                0x093f28214e172fe7,
                0x7a4108632919e6e2,
                0x41b0583cf1ed7c10,
                0xae184e0399dc776,
            ]),
        ],
        [
            Scalar::from_raw([
                0x4597e1d89615c12e,
                0xbd3d17d370ea9455,
                0x57d450ceb2260f53,
                0xcddc3d2e4b6a2f1,
            ]),
            Scalar::from_raw([
                0x933b975a5bd255bb,
                0xa31e2683ec8826a3,
                0x1c8ad14654c2ffdf,
                0xfb3cbd6e2774d03,
            ]),
            Scalar::from_raw([
                0x86fca15353910e97,
                0x66d13cbe1928b3f9,
                0x7e99b13e6641d8d4,
                0x339c59f3661533d1,
            ]),
            Scalar::from_raw([
                0x51a4d894db929922,
                0x85dbe457cfed01f3,
                0x531c1e3cba6887c3,
                0x30b7d8694db0728b,
            ]),
        ],
    ),
];

// Sponge Test Vectors

// BLS
pub(super) const BLS_SPONGE_TEST_VECTORS: [([Scalar; 12], [Scalar; 3]); 4] = [
    (
        [
            Scalar::from_raw([
                0xf2c4384cd8b0ea6e,
                0x2c61797f8b9d100f,
                0x82a589f322e32543,
                0x97cd624bc3468f1,
            ]),
            Scalar::from_raw([
                0xd353cfcbf5208931,
                0xbb4ef0c30a7e7c81,
                0xbe1e58cf79b2121d,
                0x32bc19543037b128,
            ]),
            Scalar::from_raw([
                0x712c4aa0348c906d,
                0x4170cc02369b4b51,
                0x8f8e245983e312be,
                0x574a0fe37371f412,
            ]),
            Scalar::from_raw([
                0xdcd772aa44db7b73,
                0x7d033af696a7f2cb,
                0x30a3c129cb34ab86,
                0x275c5eed364ea122,
            ]),
            Scalar::from_raw([
                0x973be4cf5724e161,
                0x88a1ed205768b244,
                0x5f170862795209e1,
                0x2258ccc789e3551d,
            ]),
            Scalar::from_raw([
                0x7acc5ce6e7cea8ed,
                0xace2e2fa44668d05,
                0x95e9e9463c116ab2,
                0x5e67b6dd3321e4ad,
            ]),
            Scalar::from_raw([
                0xbed730ad11afa3dc,
                0x57bc0dccc7f197d0,
                0x12f6d47f24e589f7,
                0x187eabe35b609a78,
            ]),
            Scalar::from_raw([
                0xf95f92c57d1f2cbe,
                0x30ffcece173962dd,
                0x17372824d02102ae,
                0x2070e1b9b5fce7b9,
            ]),
            Scalar::from_raw([
                0x52f14d18740f6cda,
                0x87b3f396b789bd31,
                0x0fe1b460063e84ac,
                0x69e42bf0ea2cc194,
            ]),
            Scalar::from_raw([
                0x4eba00f2cf6a0451,
                0x8f5d8ec515655f8a,
                0xb92b4b83dca80c9f,
                0x5e558f24e4b60455,
            ]),
            Scalar::from_raw([
                0x0ccdea3e160d34be,
                0x419247538ba716b7,
                0xfe1e2c0b303e5e6e,
                0x30643cdd431f1514,
            ]),
            Scalar::from_raw([
                0x11a008351e59eef6,
                0x3f309ccd04008824,
                0x4a5bf3bdf09ad90f,
                0x28e3cabecbb44fc6,
            ]),
        ],
        [
            Scalar::from_raw([
                0xf600746314e3f95f,
                0xa2525f53e148d54e,
                0x8d73c0567af41d66,
                0x2d9eb8ad759cd1f5,
            ]),
            Scalar::from_raw([
                0x47ff6e6a585c0bc9,
                0xe30c6d4ade7868ed,
                0x8801d6684de97bbc,
                0x432a04afcc5407,
            ]),
            Scalar::from_raw([
                0x96c773da7f70e92a,
                0xf3888a6f01b9e9aa,
                0xcd748db6c8abded7,
                0x448aca668bab642a,
            ]),
        ],
    ),
    (
        [
            Scalar::from_raw([
                0xcd9dc4885a2a22ec,
                0x5e1c7f553f49a66a,
                0x9f4c0cc188b8c4e4,
                0x2583b99cb61cb54b,
            ]),
            Scalar::from_raw([
                0xf5b477856429b448,
                0x39ce4c90a234d79a,
                0x52412e95c6e871ac,
                0x2bbce215bf22e360,
            ]),
            Scalar::from_raw([
                0x253634f8177ae344,
                0x2c2efe0f78cc9bab,
                0xbfc8f5695c0fd7fd,
                0x55a19ff4d0467ee9,
            ]),
            Scalar::from_raw([
                0x27b557936e838266,
                0x17db7b0a1baca30a,
                0x7a0b69b16827078d,
                0x30bfd7a0c0f75f5d,
            ]),
            Scalar::from_raw([
                0x204f8e441820556f,
                0x0b1c3296c5881aca,
                0x599e2e360fd1d61d,
                0x1aa863f517fe1bc,
            ]),
            Scalar::from_raw([
                0x9e96d8643efee390,
                0x2bc4f3bc3dedc38d,
                0x7fbf2008733484a9,
                0x25834128447b957e,
            ]),
            Scalar::from_raw([
                0x18df334d9aaaa079,
                0xc45b0bcc08b9e81f,
                0x12b1f5fe6d6b2992,
                0x5465c182973bdefd,
            ]),
            Scalar::from_raw([
                0xbf2042061c9ea8e4,
                0x6bba22fe4ccfca62,
                0xb6def217f22345fe,
                0x541281af939bf2bd,
            ]),
            Scalar::from_raw([
                0x74ef712372bd0a25,
                0x64730c592215567b,
                0xd70bbb20a9b0d410,
                0x4824935d586c7c31,
            ]),
            Scalar::from_raw([
                0x22ec157173f3626b,
                0x3c11f55cf422c14e,
                0x06bd49fa2e8c6daa,
                0x2d8246083c0e6466,
            ]),
            Scalar::from_raw([
                0x63d19ccc772ecd2b,
                0x18a43b2e47e6764b,
                0xda04250ced3aeaee,
                0xec4ba75e05c470f,
            ]),
            Scalar::from_raw([
                0x61884c9154f73bdf,
                0x673e2b284da0bcf7,
                0x5fee5efa3a7b2ebc,
                0x4743dfe3cec74908,
            ]),
        ],
        [
            Scalar::from_raw([
                0xeb7872ce9f8a55a7,
                0x0428689eb16df7ad,
                0xb4ba188f70ecb488,
                0x70f9f982f07f78a5,
            ]),
            Scalar::from_raw([
                0x7681281d49992b35,
                0xbbf79f7e07896558,
                0x41d369403241398c,
                0x43fd5d2e557a2d90,
            ]),
            Scalar::from_raw([
                0x5fe386a311c60c7a,
                0xe5521f969716bbf5,
                0x4b2d0452cf07a12e,
                0xeca7c8597677022,
            ]),
        ],
    ),
    (
        [
            Scalar::from_raw([
                0x839ebd799319318e,
                0x7a0a1dae9c79d6f6,
                0xefe33249b856eaf9,
                0xd2c3fc24c085a1d,
            ]),
            Scalar::from_raw([
                0xf839b35033f6cfe2,
                0xb84b34921ac44fa3,
                0xd86b2fe0f71a0e52,
                0x40f6bbaebd016d33,
            ]),
            Scalar::from_raw([
                0x56d72cd3c0e6e618,
                0xc265044c284edb5f,
                0x5c03166f198a0c65,
                0xd7ba0f823a066f9,
            ]),
            Scalar::from_raw([
                0x68d9b079820e6032,
                0x231d8c83c55c7b0d,
                0x6369a633dbfbed5a,
                0x129dcb8a8fd0ea19,
            ]),
            Scalar::from_raw([
                0xca87ddb5961beaa4,
                0x5f24caf341df414e,
                0x68b19754eee9d26b,
                0x280e1c6cf0626684,
            ]),
            Scalar::from_raw([
                0x96d326bd1d77dca1,
                0xd985f46bc3f8a634,
                0xbf7f6e699fefbf22,
                0x247a45e3a36ac6b1,
            ]),
            Scalar::from_raw([
                0x7705f55d480a24ff,
                0xc0962b9ba290b33c,
                0xc80e591f75d17903,
                0x5fa730f1a2ab3293,
            ]),
            Scalar::from_raw([
                0x2e149706bd30c04d,
                0x4b13f1059aa58e01,
                0x3aea7b41941a84f3,
                0x5bd42342d0c9e3f0,
            ]),
            Scalar::from_raw([
                0x96a50b78ca81e3fc,
                0x81e14d6fddba6acd,
                0x3aaa19c521a50612,
                0x10e58082aba5455b,
            ]),
            Scalar::from_raw([
                0xd6f0d1df74029e12,
                0x22fa44067f8f0dde,
                0x78a859c17cce6321,
                0x11b5ad9e71b2b18f,
            ]),
            Scalar::from_raw([
                0x093f28214e172fe7,
                0x7a4108632919e6e2,
                0x41b0583cf1ed7c10,
                0xae184e0399dc776,
            ]),
            Scalar::from_raw([
                0xfbd40af573e86ac8,
                0x2ed7606e94054289,
                0x4943f61868e898c8,
                0x5837deb55924a35f,
            ]),
        ],
        [
            Scalar::from_raw([
                0xb6e93562fcfe61d6,
                0xfeb8f7ddf4efca26,
                0xa23827d4773db0ee,
                0x2b096cc8fc16dde9,
            ]),
            Scalar::from_raw([
                0x2a549a19ba7a2247,
                0xd6217c03489ad66a,
                0x358d4b275795ead2,
                0x568e7993dd6f9360,
            ]),
            Scalar::from_raw([
                0x37de4a223eac43e1,
                0x4afcccae8aac7e8c,
                0x55c3eb4ed0745b40,
                0x1d77e061eb9971cc,
            ]),
        ],
    ),
    (
        [
            Scalar::from_raw([
                0x08334fef0c8df75d,
                0x56c2334323c063ec,
                0xf7ad6e9cc40dc9a0,
                0x42c712a8e874d752,
            ]),
            Scalar::from_raw([
                0x126a219bc880b5a7,
                0x3ea90c62913ab1ee,
                0xd9af4ff92442cfb5,
                0x324de6f5498e6d18,
            ]),
            Scalar::from_raw([
                0x2ff1565fbc74383e,
                0x556a4043b82ab7aa,
                0x7cfd56c2bd3b2205,
                0x5f7e1629bc91af5f,
            ]),
            Scalar::from_raw([
                0xc6b6bb0023cc2fe9,
                0x0bfae6f571c379c0,
                0x1fddfeba593bd401,
                0x1441e394376256a7,
            ]),
            Scalar::from_raw([
                0x10a4979afe865c55,
                0x72de33f1ee7b9a5d,
                0xc932cfc6c958328b,
                0x2c8ac5451be55ecf,
            ]),
            Scalar::from_raw([
                0x0808a877732a1895,
                0x89e0b5b4e9fc02e4,
                0x988c2a88226243ce,
                0x2e235a473cfef0a3,
            ]),
            Scalar::from_raw([
                0xb0c80eb2af7cfa7e,
                0xde3960eb855e0be9,
                0x17f77f2f6b3a7638,
                0x2ec2ba98c7c3a6a5,
            ]),
            Scalar::from_raw([
                0x78a293d26ca53675,
                0xa918afa864ea0112,
                0x508a9d3766cb220c,
                0x6dc8abf1172b00c8,
            ]),
            Scalar::from_raw([
                0x5236414f6e9dbd73,
                0x4af9d684845fd537,
                0x4dc41a05073f1e6a,
                0x119c8649ed47a432,
            ]),
            Scalar::from_raw([
                0x7c379555f1fe2eac,
                0x0e6e22abad4913de,
                0x28870cdb4ba35e87,
                0x52a76e355d0bda85,
            ]),
            Scalar::from_raw([
                0x2ad3554f4d0d487d,
                0x8e483ff978e24d8b,
                0x00cd0e42eb0af52f,
                0x2f61f1b5009b3edf,
            ]),
            Scalar::from_raw([
                0x02de330b333e74f1,
                0x6238df56e3cb3692,
                0xf3a432486da9b8a1,
                0x416355fa38f0833a,
            ]),
        ],
        [
            Scalar::from_raw([
                0x247c002f23627aa0,
                0x28efd11a224db357,
                0xb9550a44c6b76b82,
                0x64a2ec20f5dd489b,
            ]),
            Scalar::from_raw([
                0x07dea12d08ec21c5,
                0xe7e66895b2d41f07,
                0xb93bf23d9dd55def,
                0x6ab3c6a75e89d95b,
            ]),
            Scalar::from_raw([
                0xf2b22af5a24c77be,
                0xce72598861cf93d5,
                0x9f7a0ab4fb351521,
                0x32f066c7bf9f8e0,
            ]),
        ],
    ),
];
